apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go_hpa

spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: go_hpa
  targetCPUUtilizationPercentage: 15